server:
  port: 9090

spring:
  profiles:
    active:
      - ${ENV:dev}
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

user:
  upload:
    path: images/users/

category:
  upload:
    path: images/categories/

product:
  upload:
    path: images/products/


jwt:
  secret:
    key: 7c7ec2de71a50014c861085fa916e0c64f1d7edcf7b91cbbeaaf9e364aeae6cd
  expiry:
    time: 86400000

#86400000

razorpay:
  secret:
    id: rzp_test_IOCh6tAQLEKrid
    key: oObriJL1cKlcwHJfYMoX0OSS


